version:
  name: velociraptor
  version: 0.7.1
  commit: "0746831"
  build_time: "2023-12-13T10:45:43Z"
  install_time: 1703723236
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/7194076107
  compiler: go1.21.4
Client:
  server_urls:
  - https://logger:9000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQN4fZg6knR/AfC7sntScPEzANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjMxMjI4MDAyNzM1WhcNMzMx
    MjI1MDAyNzM1WjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC/rUsMqTWeHpc6i7qWH8PBYWxLKo3+YBP4
    2oCsaXfkBqAfIxdX0SMipTnO/CjhGuElt8FFrg+pkwEt5Q3HYcMmIgIEHN/Z5Ei8
    mXBFaJ76BYEmPhuCEVwqC9CkD/Y4kr9l3V5sBnZn2P6dkywVOFGb1uWyvPZNON93
    032z6TYK4efX4Q3t9ZSDcwUiVpGmTT9ZI1r6iA9lzxyu3S5LvZmOXBIC46CD75C7
    v7N7W3HK5tJvN2RPxGXrr57QL5YgFEz9nmi1hu2j880tHnyG+79fSCYa0dKx5md7
    1NPGWQGXJ8dnMr8eljCWGzPWKLgzTinD+v9k2oAsoBwbGNtOnMY5AgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSeJwyBm/861VL817l6e8LLDHz7
    KzAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAekM+xqAu98eCYux9qf+CKTfxD5r/0PPaO1S/q61FW21d
    LS6drDPVt7E7+W8l5LaM1pGbvjYHiO78rLXCmE7Qa9/1Mu+8iTP+PECUxLYgko6s
    Ja14F9t58sGH9bH32qtodREhbjr8pHa5ApmWy+2Z0oeWMkZqLkeZjiFihegTsqgh
    vynPF0rtrpNeeSjIIbUt/908NZG3zQlnfOfIt1T/E/GBacmLIY2ODYvT8qU2SXE/
    U7mGP1QYuJB3NTT+f1a2gnOsYc1zLZXDtldl0g9A3aZf4x18WtJZ0D+3AsUUrC17
    wblFOAUOwcnJiUVHu/d5/rwI1gPCVcMDV2/RubvYpw==
    -----END CERTIFICATE-----
  nonce: SNxvwYd+UBM=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.7.1
    commit: "0746831"
    build_time: "2023-12-13T10:45:43Z"
    install_time: 1703723236
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/7194076107
    compiler: go1.21.4
  use_self_signed_ssl: true
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin
