---

- name: Hostname -> win2016base
  win_hostname:
    name: win2016base
  register: res

- name: Reboot
  win_reboot:
  when: res.reboot_required
  
- name: Check for Chocolatey Directory
  win_stat:
    path: 'C:\ProgramData\Chocolatey'
  register: choco_dir

- name: Fetch .NET offline installer - Required for Chocolatey
  win_shell: wget -uri https://download.visualstudio.microsoft.com/download/pr/2d6bb6b2-226a-4baa-bdec-798822606ff1/8494001c276a4b96804cde7829c04d7f/ndp48-x86-x64-allos-enu.exe -outfile c:\windows\temp\dot_net_install.exe
  when: not choco_dir.stat.exists

- name: Silent install of .NET framework - Required for Chocolatey
  win_shell: C:\Windows\Temp\dot_net_install.exe /q
  register: install_dot_net
  when: not choco_dir.stat.exists

- name: wait for reboot post .NET install
  wait_for_connection:
    delay: 30
  when: not install_dot_net is skipped

- name: Install Chocolatey
  win_shell: "Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))"
  when: not choco_dir.stat.exists

- name: Install git
  win_chocolatey:
    name: git
    state: present

- name: Check if existing DetectionLab directory
  win_stat:
    path: 'c:\DetectionLab'
  register: dir

- name: Git clone Detectionlab
  win_shell: git clone https://github.com/MaximumPigs/DetectionLab.git
  args:
    chdir: 'c:\'
  when: not dir.stat.exists

- name: Delete old vagrant folder
  win_shell: if (Test-Path -Path c:\vagrant\) { try {Remove-Item -Path c:\vagrant\ -Recurse -Force} catch [System.ComponentModel.Win32Exception] { $(Get-Item C:\vagrant\).delete() }}

- name: Copy scripts to c:\vagrant
  win_shell: Copy-Item -Recurse c:\DetectionLab\Vagrant c:\vagrant

- name: Configure with raw Commands
  win_shell: "{{ item }}"
  with_items:
    - "wevtutil el | Select-String -notmatch \"Microsoft-Windows-LiveId\" | Foreach-Object {wevtutil cl \"$_\"}"
    - "Set-SmbServerConfiguration -AuditSmb1Access $true -Force"


