name: 'Get Cost'

on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  get_cost:
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init AWS
      working-directory: ./AWS/Terraform
      run: terraform init -backend-config="backend.hcl"

    # Gets Terraform state and generates cost using cost.modules.tf
    - name: Terraform Get Cost AWS
      id: cost
      working-directory: ./AWS/Terraform
      run: |
       state=$(terraform state pull)
       json=$(curl -s -X POST -H "Content-Type: application/json" -d $state https://cost.modules.tf/)
       echo "json_cost=$json" >> $GITHUB_OUTPUT

    - name: Convert JSON to Markdown
      uses: buildingcash/json-to-markdown-table-action@v1
      id: table
      with:
        json: ${{ steps.cost.outputs.json_cost }}
    
    - name: Send table to output
      run: echo ${{ steps.table.outputs.table }} >> $GITHUB_STEP_SUMMARY"
